version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: coverahealth.jfrog.io/ai-development-docker/ishita/radfm:latest
    platform: linux/amd64